name: Run CI checks

on: [pull_request]

jobs:
  install:
    runs-on: ubuntu-latest
    name: Install deps
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - run: yarn run nx affected --target=lint
  # build:
  #   runs-on: ubuntu-latest
  #   name: Building affected apps
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: borales/actions-yarn@v2.3.0
  #     - run: yarn run nx affected --target=build --base=origin/main --parallel --skip-nx-cache
  # test:
  #   runs-on: ubuntu-latest
  #   name: Testing affected apps
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: borales/actions-yarn@v2.3.0
  #     - run: yarn run nx affected --target=test --base=origin/main --parallel --skip-nx-cache
  # lint:
  #   runs-on: ubuntu-latest
  #   name: Linting affected apps
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: borales/actions-yarn@v2.3.0
  #     - run: yarn run nx affected --target=lint --base=origin/main --parallel --skip-nx-cache
  # e2e:
  #   runs-on: ubuntu-latest
  #   name: E2E testing affected apps
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: borales/actions-yarn@v2.3.0
  #     - run: yarn run nx affected --target=e2e --base=origin/main --parallel --skip-nx-cache